<div class="row z-depth-5">
	<h2 class="center-align">Lista de Categorias</h2>
	<div class="row">
          
		<div class="container right-align">
			<a href="<?php echo APP_URL."tareas"; ?>" class="brand-logo"><i class="material-icons">home</i></a>
			<a class="waves-effect waves-light btn" href="<?php echo APP_URL."categorias/agregar"; ?>"><i class="material-icons left">add</i>Categoria</a>
		</div>
		<div class="row">
			<table class="highlight">
				<thead>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
				    <?php foreach ($this->categorias as $categoria): ?>
                        <tr>
                           <td><?php  echo $categoria['id'];?></td>
					       <td><?php  echo $categoria['nombre'];?></td>
                            <td>
                            	<a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>"><i class="material-icons">edit</i></a>
                            	<a class="modal-trigger" href="#modal1" ><i class="material-icons">delete</i></a>
                            	 <div id="modal1" class="modal">
								    <div class="modal-content">
								      <p>Desea eliminar el registro</p>
								    </div>
								    <div class="modal-footer">
								   		<a class="modal-close waves-effect waves-green btn-flat">Cancelar</a>
								      	<a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>" class="modal-close waves-effect waves-green btn-flat">Aceptar</a>
								    </div>
								  </div>

                            </td>
                        </tr>
                    <?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
